Assignments/recursion
bhs-intro-to-programming/AvaGoesCrazy pull request #38
Opened 2023-04-12 22:30 UTC by AvaGoesCrazy

not all finished but im working on it

2023-04-13 03:33 UTC, gigamonkey requested changes
Good progress. Keep going!

2023-04-13 03:33 UTC, gigamonkey commented on assignments/recursion/code.js
> +    return sum(ary.slice(1)) + ary[ary.length - 1]
This is not quite right because `ary.slice(1)` slices from the 1st index (i.e. the second position, after index 0) to the end of the array and thus includes the element at position `ary.length - 1` but does _not_ include the element at position `0` so you've lost the 0th item and have included the last item twice.

2023-04-13 03:33 UTC, gigamonkey commented on assignments/recursion/code.js
> +  if(ary[1] === n){
Close, but remember that `ary[1]` is the second element of the array, not the first.

2023-04-13 22:29 UTC, AvaGoesCrazy commented
More changes done, reverseString is kinda scuffed but it works. Two more to go!

2023-04-19 01:14 UTC, gigamonkey approved these changes
Nice work. Techncially `sum` and `reverseString` should use a zero length array or string as the base case: for `sum` the sum of 0 elements is 0 and the empty string reverses to itself. It might seem silly for someone to call those functions with an empty array or an empty string but since there's a well defined result it makes sense to handle them. But other than that nit, this all looks good.

I'd recommend tackling the 2nd recursion problem set before you worry about change—it's quite a bit harder than the others though it is a great test of recursive thinking.

2023-04-24 22:18 UTC, merged